application/views/booking_views.py
from flask import redirect, url_for, render_template, Blueprint, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user
from application.forms.booking_forms import BookingForm
from application.models import Booking, Show
from application.database import db
from datetime import datetime
from application.views.show_views import calculate_static_rating

booking_bp = Blueprint("booking", __name__)

# prefix of /book has been applied for this blueprint


@booking_bp.route("/register/<int:show_id>", methods=["POST"])
@login_required
def register(show_id):
    form = BookingForm()
    show = Show.query.get(show_id)

    if form.validate_on_submit():
        num_tickets = form.num_tickets.data

        if show.unsold_tickets >= num_tickets:
            new_booking = Booking(user_id=current_user.id, show_id=show_id, num_tickets=num_tickets)
            db.session.add(new_booking)

            show.unsold_tickets -= num_tickets
            show.rating += calculate_dynamic_rating(show)
            show.rating = min(5, show.rating)

            try:
                db.session.commit()
                flash("Booking successful!", "success")
                return redirect(url_for("user.dashboard"))
            except IntegrityError as e:
                db.session.rollback()
                if "foreign key constraint" in str(e).lower():
                    flash("The provided show does not exist.", "warning")
                else:
                    flash("Booking unsuccessful", "warning")
        else:
            flash(f"Only {show.unsold_tickets} tickets are available!", "warning")

    for field_name, field in form._fields.items():
        if field.errors:
            for error in field.errors:
                flash(f"{field.label.text} error: {error}", "warning")

    return render_template("show/show.html", show=show, form=form)


@booking_bp.route("/delete/<int:id>", methods=["POST"])
@login_required  # only for user
def delete(id):
    booking = Booking.query.get_or_404(id)
    show = booking.show
    show.unsold_tickets += booking.num_tickets
    show.rating = calculate_static_rating(show.start_time, show.end_time, show.ticket_price) + calculate_dynamic_rating(
        show
    )
    db.session.delete(booking)

    try:
        db.session.commit()
        flash("Booking successfully deleted", "success")
        return redirect(url_for("user.dashboard"))
    except Exception as e:
        flash("Error in deleting booking", "warning")
        return redirect(url_for("user.dashboard"))


def calculate_dynamic_rating(show):
    time_elapsed_seconds = (datetime.utcnow() - show.created_at).seconds

    # Calculate the rate of tickets sold
    sold_tickets = show.venue.capacity - show.unsold_tickets
    tickets_sold_per_second = sold_tickets / time_elapsed_seconds

    max_rate = 1 / 3600  # Assuming the max rate is 1 ticket sold per hour
    rating = min(tickets_sold_per_second / max_rate, 1) * 2
    rating += sold_tickets / show.venue.capacity

    return round(min(rating, 3), 2)

application/views/show_views.py
from flask import request, redirect, url_for, render_template, Blueprint, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user
from application.forms.show_forms import RegistrationForm, EditForm
from application.forms.booking_forms import BookingForm
from application.models import Show, Venue, User, Booking
from application.database import db
from application.decorators import admin_required

show_bp = Blueprint("show", __name__)

# prefix of /show has been applied for this blueprint


@show_bp.route("/register", methods=["GET", "POST"])  # Create a new venue
@login_required
@admin_required
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        venue = Venue.query.get(form.venue_id.data)
        rating = calculate_static_rating(form.start_time.data, form.end_time.data, form.ticket_price.data)

        new_show = Show(
            name=form.name.data,
            tags=form.tags.data,
            ticket_price=form.ticket_price.data,
            venue_id=form.venue_id.data,
            start_time=form.start_time.data,
            end_time=form.end_time.data,
            description=form.description.data,
            unsold_tickets=venue.capacity,
            rating=rating,
        )
        db.session.add(new_show)

        try:
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            if "foreign key constraint" in str(e).lower():
                flash("The provided venue does not exist.", "warning")
            else:
                flash("Registration unsuccessful", "warning")

            return redirect(url_for("show.register"))
        flash("Show registered successfully!", "success")
        venue_id = request.form.get("venue_id", None)
        if venue_id:
            return redirect(url_for("venue.venue", id=venue_id))
        return redirect(url_for("user.dashboard"))
    elif request.method == "POST":
        for field_name, field in form._fields.items():
            if field.errors:
                for error in field.errors:
                    flash(f"{field.label.text} error: {error}", "warning")

    id = request.args.get("id", None)  # get('param_name',default)
    return render_template("show/register.html", form=form, venue_id=id)


@show_bp.route("/<int:id>", methods=["GET", "POST"])
# render show page as well allow edits (edit button should be shown only for admins)
@login_required  # may have to redirect role="user" post requests to some error page
def show(id):
    show = Show.query.get_or_404(id)
    form = EditForm()

    if current_user.role == "user":  # even if user sends post request, only non-editable page will be displayed
        return render_template("show/show.html", show=show, form=BookingForm())
    else:
        if form.validate_on_submit():
            show = Show.query.get(id)

            show.tags = form.tags.data
            show.description = form.description.data

            try:  # db constraints validations
                db.session.commit()
            except IntegrityError as e:
                db.session.rollback()
                flash("Registration unsuccessful", "warning")
                return redirect(url_for("show.show", id=id))
            flash("Edit successful!", "success")
            return redirect(url_for("show.show", id=id))
        elif request.method == "POST":
            for field_name, field in form._fields.items():
                if field.errors:
                    for error in field.errors:
                        flash(f"{field.label.text} error: {error}", "warning")
    form.process(obj=show)  # display editable show page for admin get request
    return render_template("show/show_admin.html", show=show, form=form)


@show_bp.route("/delete/<int:id>", methods=["POST"])
@login_required
@admin_required
def delete(id):
    show = Show.query.get_or_404(id)

    if show.bookings:
        # If shows are associated with the venue, return an error message
        flash(
            "Cannot delete a show with associated bookings. Please remove all bookings before deleting the show.",
            "danger",
        )
        return redirect(url_for("show.show", id=id))

    # If no shows are associated, delete the venue and redirect back to the dashboard
    db.session.delete(show)
    try:
        db.session.commit()
        flash("Show successfully deleted.", "success")
        return redirect(url_for("user.dashboard"))
    except Exception as e:
        flash("Error in deleting show", "warning")
        return redirect(url_for("show.show", id=id))


@show_bp.route("/filter")
@login_required
def filter():
    name = request.args.get("name", None)
    tag = request.args.get("tag", None)
    rating = request.args.get("rating", None)
    start_datetime = request.args.get("start_datetime", None)
    end_datetime = request.args.get("end_datetime", None)
    min_price = request.args.get("min_price", None)
    max_price = request.args.get("max_price", None)

    query = Show.query

    if name:
        query = query.filter(Show.name == name)
    if tag:
        query = query.filter(Show.tags.ilike(f"%{tag}%"))
    if rating:
        query = query.filter((Show.rating >= int(rating) - 1) & (Show.rating <= int(rating) + 1))
    if start_datetime:
        query = query.filter(Show.start_time >= start_datetime)
    if end_datetime:
        query = query.filter(Show.end_time <= end_datetime)
    if min_price:
        query = query.filter(Show.ticket_price >= int(min_price))
    if max_price:
        query = query.filter(Show.ticket_price <= int(max_price))

    venues = Venue.query.all()
    shows = query.all()
    users = User.query.all()
    bookings = Booking.query.all() if current_user.role == "admin" else current_user.bookings

    return render_template("user/dashboard.html", venues=venues, shows=shows, bookings=bookings, users=users)


# Static part of rating (2 points) calculated at show creation
def calculate_static_rating(start_time, end_time, price):
    rating = 0

    duration = (end_time - start_time).seconds / 3600
    optimal_duration = 2.5
    rating += max(1 - abs(duration - optimal_duration) / optimal_duration, 0)

    optimal_price = 500

    if price <= optimal_price:
        rating += 1
    else:
        rating += max(1 - (price - optimal_price) / optimal_price, 0)  # rating of 0  at twice the optimal price
    return round(rating, 2)

application/views/user_views.py
from flask import request, redirect, url_for, render_template, Blueprint, flash
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, login_required, logout_user, current_user
from application.forms.user_forms import RegistrationForm, LoginForm, EditForm
from application.models import User, Show, Venue, Booking
from application.database import db
from application.decorators import admin_required

user_bp = Blueprint("user", __name__)  # (blueprint_name, module_name)


@user_bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("user.dashboard"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)  # flask-login library
            return redirect(url_for("user.dashboard"))
        else:
            flash("Invalid username or password.", "warning")
    return render_template("user/login.html", form=form)


@user_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        new_user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            role="user",
            mobile_number=form.mobile_number.data,
            dob=form.dob.data,
            gender=form.gender.data,
        )
        db.session.add(new_user)
        try:  # db constraints validations
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            if "UNIQUE constraint failed: user.username" in str(e):
                flash("Registration unsuccessful: Username already exists", "warning")
            if "UNIQUE constraint failed: user.email" in str(e):
                flash(
                    "Registration unsuccessful: Email already exists", "warning"
                )  # Only the latest flashed message gets printed onto webpage ....dk why...dw too much...whereas in the below elif snipped all flashed messages get printed
            if "UNIQUE constraint failed: user.mobile_number" in str(e):
                flash("Registration unsuccessful: Mobile number already exists", "warning")
            return redirect(url_for("user.register"))
        flash("Registration successful! Please log in.", "success")  # (message,category)
        return redirect(url_for("user.login"))
    elif request.method == "POST":
        # if form.password.errors or form.confirm_password.errors:
        #     for error in form.password.errors + form.confirm_password.errors:
        #         flash(f"Password error: {error}", "warning")
        # if form.mobile_number.errors:
        #     for error in form.mobile_number.errors:
        #         flash(f"Mobile Number error: {error}", "warning")
        for field_name, field in form._fields.items():
            if field.errors:
                for error in field.errors:
                    flash(f"{field.label.text} error: {error}", "warning")

    return render_template("user/register.html", form=form)  # get request


@user_bp.route("/user", methods=["GET", "POST"])
@login_required
def profile():
    form = EditForm()  # pass current_user if you are using constructor initialization instead of form.process
    if form.validate_on_submit():
        flag = False  # Will be set if password/username is changed
        user = User.query.get(current_user.id)
        user.email = form.email.data
        if form.dob.data is not None:
            user.dob = form.dob.data
        if form.mobile_number.data:
            user.mobile_number = form.mobile_number.data
        if form.old_password.data and form.new_password.data:
            current_user.password = generate_password_hash(form.new_password.data)
            flag = True
        user.gender = form.gender.data
        if current_user.username != form.username.data:
            flag = True
            user.username = form.username.data

        try:  # db constraints validations
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            if "UNIQUE constraint failed: user.email" in str(e):
                flash("Edit unsuccessful: Email already exists", "warning")
            if "UNIQUE constraint failed: user.mobile_number" in str(e):
                flash("Edit unsuccessful: Mobile number already exists", "warning")
            if "UNIQUE constraint failed: user.username" in str(e):
                flash("Edit unsuccessful: Username already exists", "warning")
            return redirect(url_for("user.profile"))
        flash("Edit successful!", "success")  # (message,category)
        if flag:
            logout_user()
            return redirect(url_for("user.login"))
        return redirect(url_for("user.profile"))
    elif request.method == "POST":
        for field_name, field in form._fields.items():
            if field.errors:
                for error in field.errors:
                    flash(f"{field.label.text} error: {error}", "warning")
    form.process(obj=current_user)
    # Automatically matches input names and attributes of current_user tuple to fill up the form... uses placeholders for some and values for others...can't seem to override this behaviour
    return render_template("user/profile.html", form=form)


@user_bp.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("user.login"))


@user_bp.route("/dashboard")
@login_required
def dashboard():  # All venues,bookings,shows will be displayed
    shows = Show.query.all()
    venues = Venue.query.all()
    users = User.query.all()
    bookings = Booking.query.all() if current_user.role == "admin" else current_user.bookings

    return render_template("user/dashboard.html", venues=venues, shows=shows, bookings=bookings, users=users)


@user_bp.route("/delete", methods=["POST"])
@login_required
def delete():
    try:
        user = User.query.get(current_user.id)

        # Delete all bookings associated with the user
        bookings = Booking.query.filter_by(user_id=current_user.id).all()
        for booking in bookings:
            db.session.delete(booking)

        # Delete the user
        db.session.delete(user)
        db.session.commit()

        flash("Your account and bookings have been deleted.", "success")
        return redirect(url_for("user.login"))

    except Exception as e:
        db.session.rollback()
        flash("An error occurred while trying to delete your account. Please try again.", "warning")
        return redirect(url_for("user.profile"))


@user_bp.route("/get")
@login_required
@admin_required
def user():
    user_id = request.args.get("user_id", None)
    if user_id:
        user = User.query.get(user_id)
        return render_template("user/user.html", user=user)
    return redirect("user.dashboard")

application/templates/user/dashboard.html
{% extends "base.html" %}
{% block title %}
Dashboard
{% endblock %}

<!-- {% block styles%}
<style>
    .horizontal-scroll {
        overflow-x: auto;
        white-space: nowrap;
    }
</style>
{%endblock%} -->

{% block content %}

<div class="container">

    <section>
        <div class="row my-4">
            <div class="col-md-3">
                <h2>Venues</h2>
            </div>
            <div class="col-md-9 d-flex justify-content-end align-items-center">
                {% if current_user.role == "admin" %}
                <a href="{{url_for('venue.register')}}" class="btn btn-primary btn-sm me-3">Add Venue</a>
                {% endif %}
                <form action="{{url_for('venue.filter')}}" method="get">
                    Filter:
                    <input type="text" name="name" placeholder="Venue Name">
                    <input type="text" name="city" placeholder="City">
                    <input type="text" name="state" placeholder="State">
                    <button class="btn btn-primary btn-sm">filter</button>
                </form>
            </div>
        </div>
        <div class="row">
            {% for venue in venues %}
            <div class="col-md-4 col-lg-3 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{url_for('venue.venue', id=venue.id)}}">{{venue.name}}</a>
                        </h5>
                        <p class="card-text">
                            {{ venue.city }}, {{ venue.state }}
                        </p>
                        <p class="card-text">
                            {{ venue.mobile_number }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <div class="row my-4">
            <div class="col-md-3">
                <h2>Shows</h2>
            </div>
            <div class="col-md-9 d-flex justify-content-end align-items-center">
                {% if current_user.role == "admin" %}
                <a href="{{ url_for('show.register') }}" class="btn btn-primary btn-sm me-3">Add Show</a>
                {% endif %}
                <form action="{{url_for('show.filter')}}" method="get">
                    Filter:
                    <input type="text" name="name" placeholder="Show Name">
                    <input type="text" name="tag" placeholder="Tag">
                    Rating:
                    <input type="text" name="rating" placeholder="Approx rating">
                    Date and Time Range:
                    <input type="datetime-local" name="start_datetime" title="Start Date and Time">
                    <input type="datetime-local" name="end_datetime" title="End Date and Time">
                    <br>Price Range:
                    <input type="text" name="min_price" placeholder="Minimum Price">
                    <input type="text" name="max_price" placeholder="Maximum Price">
                    <button class="btn btn-primary btn-sm">filter</button>
                </form>

            </div>
        </div>
        <!-- <div class="horizontal-scroll"> -->
        <div class="row">
            <!-- Loop through all shows and display them in a card format -->
            {% for show in shows %}
            <div class="col-md-5 col-lg-3 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{url_for('show.show', id=show.id)}}">{{ show.name }}</a> {{ show.rating|round(2)
                            }}/5.0
                        </h5>
                        <p class="card-text">
                            {{ show.tags }}
                        </p>
                        <p class="card-text">
                            Price: ${{ show.ticket_price }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <div class="row my-4">
            <div class="col-md-3">
                <h2>Bookings</h2>
            </div>
        </div>
        <div class="row">
            {% for booking in bookings %}
            <div class="col-md-5 col-lg-3 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{url_for('show.show', id=booking.show.id)}}">{{ booking.show.name }}</a>
                        </h5>

                        <p class="card-text">
                            Number of tickets: {{ booking.num_tickets }}
                        </p>
                        <p class="card-text">
                            Date and time: {{ booking.show.start_time.strftime('%-d %b %-I%p') }}
                        </p>
                        {%if current_user.role=="admin"%}
                        <p class="card-text">User: <a
                                href="{{url_for('user.user',user_id=booking.user.id)}}">{{booking.user.username}}</a>
                        </p>
                        {%else%}
                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal"
                            data-booking-id="{{booking.id}}">Delete
                            Booking</button>
                        {%endif%}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- booking.id is dynamically passed to the modal with the help of data-* attribute and js-->
    <!-- This is because booking object is not accessible outside the loop but modal has to be present outside efficiency -->
    <!-- putting modal def inside loop is not efficient due to redundant html code  -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Booking</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this booking? This action cannot be undone. Only 50% of the total
                    ticket price will be refunded.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <form method="POST">
                        <input type="submit" value="Delete Booking" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
    </div>


    {%if current_user.role=="admin"%}
    <section>
        <div class="row my-4">
            <div class="col-md-3">
                <h2>Users</h2>
            </div>
        </div>
        <div class="row">
            {% for user in users %}
            <div class="col-md-5 col-lg-3 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{url_for('user.user', user_id=user.id)}}">{{ user.username }}</a>
                        </h5>
                        <p class="card-text">
                            Role: {{ user.role }}
                        </p>
                        <p class="card-text">
                            Mobile Number {{ user.mobile_number}}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    {%endif%}

</div>
{% endblock %}

{% block scripts %}
<script>
    const deleteModal = document.getElementById('deleteModal');
    const deleteForm = deleteModal.querySelector('form');
    const deleteButtons = document.querySelectorAll('[data-booking-id]');

    deleteButtons.forEach(button => {
        button.addEventListener('click', (event) => {
            const bookingId = event.target.getAttribute('data-booking-id');
            deleteForm.action = "{{ url_for('booking.delete', id=0) }}".replace('/0', '/' + bookingId);
        });
    });
</script>
{% endblock %}

application/templates/user/login.html
{% extends "base.html" %}
{% block title %}Log In{% endblock %}
{% block content %}
<div class="container">
    <h1 class="text-center my-4">Log In</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ url_for('user.login') }}" novalidate>
                        {{ form.hidden_tag() }}
                        <div class="form-floating mb-3">
                            {{ form.username(class="form-control", placeholder="Username") }}
                            {{ form.username.label(class="form-label") }}
                        </div>
                        <div class="form-floating mb-3">
                            {{ form.password(class="form-control", placeholder="Password") }}
                            {{ form.password.label(class="form-label") }}
                        </div>
                        <div class="d-grid">
                            {{ form.log_in(class="btn btn-primary") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-4">
        <div class="col-md-6 text-center">
            <p>Don't have an account? <a href="{{url_for('user.register')}}">Register</a></p>
        </div>
    </div>
</div>
{% endblock %}

application/templates/user/profile.html
{% extends "base.html" %}
<!-- Someother things which could be added -> History of shows booked...some graph showing show booking pattern? -->
{% block content %}
<div class="container">
    <h1 class="my-4">Profile</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">User Details</h5>
            <form action="{{ url_for('user.profile') }}" method="post" class="mb-2">
                {{ form.hidden_tag() }}
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th scope="row">{{form.username.label}}</th>
                            <td>{{ form.username }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.old_password.label}}</th>
                            <td>{{ form.old_password }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.new_password.label}}</th>
                            <td>{{ form.new_password }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.email.label}}</th>
                            <td>{{form.email}} </td>
                        </tr>
                        <tr>
                            <th scope="row">Role</th>
                            <td>{{ current_user.role }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Joined</th>
                            <td>{{ current_user.created_at.strftime('%Y-%m-%d') }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.dob.label}}</th>
                            <td>{{form.dob}}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.gender.label}}</th>
                            <td>{{form.gender}}
                            </td>
                        </tr>
                        <tr>
                            <th scope="row"><label for="mobile_number">Mobile Number</label></th>
                            <td><input type="text" name="mobile_number" id="mobile_number"
                                    placeholder="{{ current_user.mobile_number }}"></td>
                        </tr>
                    </tbody>
                </table>
                <button class="btn btn-primary">Apply Changes</button>
            </form>
            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete
                Account</button>
        </div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your account? This action cannot be undone.
                All your bookings will be lost!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{{ url_for('user.delete', id=current_user.id) }}" method="POST">
                    {{ form.hidden_tag() }}
                    <input type="submit" value="Delete Account" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}