application/forms/show_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, TextAreaField, FloatField, DateTimeLocalField
from wtforms.validators import DataRequired, Length, ValidationError


class RegistrationForm(FlaskForm):
    name = StringField("Name*", validators=[DataRequired(), Length(min=2, max=80)])
    tags = StringField("Tags", validators=[Length(max=255)])
    ticket_price = FloatField("Ticket Price*", validators=[DataRequired()])
    venue_id = IntegerField("Venue ID*", validators=[DataRequired()])
    start_time = DateTimeLocalField("Start Time*", format="%Y-%m-%dT%H:%M", validators=[DataRequired()])
    end_time = DateTimeLocalField("End Time*", format="%Y-%m-%dT%H:%M", validators=[DataRequired()])

    description = TextAreaField("Description", validators=[Length(max=200)])
    submit = SubmitField("Create Show")

    def validate_start_time(form, field):
        if form.start_time.data >= form.end_time.data:
            raise ValidationError("Start time must be earlier than the end time.")


class EditForm(FlaskForm):
    tags = StringField("Tags", validators=[Length(max=255)])
    description = TextAreaField("Description", validators=[Length(max=200)])

    submit = SubmitField("Apply Changes")

application/views/booking_views.py
from flask import redirect, url_for, render_template, Blueprint, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user
from application.forms.booking_forms import BookingForm
from application.models import Booking, Show
from application.database import db
from datetime import datetime
from application.views.show_views import calculate_static_rating

booking_bp = Blueprint("booking", __name__)

# prefix of /book has been applied for this blueprint


@booking_bp.route("/register/<int:show_id>", methods=["POST"])
@login_required
def register(show_id):
    form = BookingForm()
    show = Show.query.get(show_id)

    if form.validate_on_submit():
        num_tickets = form.num_tickets.data

        if show.unsold_tickets >= num_tickets:
            new_booking = Booking(user_id=current_user.id, show_id=show_id, num_tickets=num_tickets)
            db.session.add(new_booking)

            show.unsold_tickets -= num_tickets
            show.rating += calculate_dynamic_rating(show)
            show.rating = min(5, show.rating)

            try:
                db.session.commit()
                flash("Booking successful!", "success")
                return redirect(url_for("user.dashboard"))
            except IntegrityError as e:
                db.session.rollback()
                if "foreign key constraint" in str(e).lower():
                    flash("The provided show does not exist.", "warning")
                else:
                    flash("Booking unsuccessful", "warning")
        else:
            flash(f"Only {show.unsold_tickets} tickets are available!", "warning")

    for field_name, field in form._fields.items():
        if field.errors:
            for error in field.errors:
                flash(f"{field.label.text} error: {error}", "warning")

    return render_template("show/show.html", show=show, form=form)


@booking_bp.route("/delete/<int:id>", methods=["POST"])
@login_required  # only for user
def delete(id):
    booking = Booking.query.get_or_404(id)
    show = booking.show
    show.unsold_tickets += booking.num_tickets
    show.rating = calculate_static_rating(show.start_time, show.end_time, show.ticket_price) + calculate_dynamic_rating(
        show
    )
    db.session.delete(booking)

    try:
        db.session.commit()
        flash("Booking successfully deleted", "success")
        return redirect(url_for("user.dashboard"))
    except Exception as e:
        flash("Error in deleting booking", "warning")
        return redirect(url_for("user.dashboard"))


def calculate_dynamic_rating(show):
    time_elapsed_seconds = (datetime.utcnow() - show.created_at).seconds

    # Calculate the rate of tickets sold
    sold_tickets = show.venue.capacity - show.unsold_tickets
    tickets_sold_per_second = sold_tickets / time_elapsed_seconds

    max_rate = 1 / 3600  # Assuming the max rate is 1 ticket sold per hour
    rating = min(tickets_sold_per_second / max_rate, 1) * 2
    rating += sold_tickets / show.venue.capacity

    return round(min(rating, 3), 2)

application/views/show_views.py
from flask import request, redirect, url_for, render_template, Blueprint, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user
from application.forms.show_forms import RegistrationForm, EditForm
from application.forms.booking_forms import BookingForm
from application.models import Show, Venue, User, Booking
from application.database import db
from application.decorators import admin_required

show_bp = Blueprint("show", __name__)

# prefix of /show has been applied for this blueprint


@show_bp.route("/register", methods=["GET", "POST"])  # Create a new venue
@login_required
@admin_required
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        venue = Venue.query.get(form.venue_id.data)
        rating = calculate_static_rating(form.start_time.data, form.end_time.data, form.ticket_price.data)

        new_show = Show(
            name=form.name.data,
            tags=form.tags.data,
            ticket_price=form.ticket_price.data,
            venue_id=form.venue_id.data,
            start_time=form.start_time.data,
            end_time=form.end_time.data,
            description=form.description.data,
            unsold_tickets=venue.capacity,
            rating=rating,
        )
        db.session.add(new_show)

        try:
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            if "foreign key constraint" in str(e).lower():
                flash("The provided venue does not exist.", "warning")
            else:
                flash("Registration unsuccessful", "warning")

            return redirect(url_for("show.register"))
        flash("Show registered successfully!", "success")
        venue_id = request.form.get("venue_id", None)
        if venue_id:
            return redirect(url_for("venue.venue", id=venue_id))
        return redirect(url_for("user.dashboard"))
    elif request.method == "POST":
        for field_name, field in form._fields.items():
            if field.errors:
                for error in field.errors:
                    flash(f"{field.label.text} error: {error}", "warning")

    id = request.args.get("id", None)  # get('param_name',default)
    return render_template("show/register.html", form=form, venue_id=id)


@show_bp.route("/<int:id>", methods=["GET", "POST"])
# render show page as well allow edits (edit button should be shown only for admins)
@login_required  # may have to redirect role="user" post requests to some error page
def show(id):
    show = Show.query.get_or_404(id)
    form = EditForm()

    if current_user.role == "user":  # even if user sends post request, only non-editable page will be displayed
        return render_template("show/show.html", show=show, form=BookingForm())
    else:
        if form.validate_on_submit():
            show = Show.query.get(id)

            show.tags = form.tags.data
            show.description = form.description.data

            try:  # db constraints validations
                db.session.commit()
            except IntegrityError as e:
                db.session.rollback()
                flash("Registration unsuccessful", "warning")
                return redirect(url_for("show.show", id=id))
            flash("Edit successful!", "success")
            return redirect(url_for("show.show", id=id))
        elif request.method == "POST":
            for field_name, field in form._fields.items():
                if field.errors:
                    for error in field.errors:
                        flash(f"{field.label.text} error: {error}", "warning")
    form.process(obj=show)  # display editable show page for admin get request
    return render_template("show/show_admin.html", show=show, form=form)


@show_bp.route("/delete/<int:id>", methods=["POST"])
@login_required
@admin_required
def delete(id):
    show = Show.query.get_or_404(id)

    if show.bookings:
        # If shows are associated with the venue, return an error message
        flash(
            "Cannot delete a show with associated bookings. Please remove all bookings before deleting the show.",
            "danger",
        )
        return redirect(url_for("show.show", id=id))

    # If no shows are associated, delete the venue and redirect back to the dashboard
    db.session.delete(show)
    try:
        db.session.commit()
        flash("Show successfully deleted.", "success")
        return redirect(url_for("user.dashboard"))
    except Exception as e:
        flash("Error in deleting show", "warning")
        return redirect(url_for("show.show", id=id))


@show_bp.route("/filter")
@login_required
def filter():
    name = request.args.get("name", None)
    tag = request.args.get("tag", None)
    rating = request.args.get("rating", None)
    start_datetime = request.args.get("start_datetime", None)
    end_datetime = request.args.get("end_datetime", None)
    min_price = request.args.get("min_price", None)
    max_price = request.args.get("max_price", None)

    query = Show.query

    if name:
        query = query.filter(Show.name == name)
    if tag:
        query = query.filter(Show.tags.ilike(f"%{tag}%"))
    if rating:
        query = query.filter((Show.rating >= int(rating) - 1) & (Show.rating <= int(rating) + 1))
    if start_datetime:
        query = query.filter(Show.start_time >= start_datetime)
    if end_datetime:
        query = query.filter(Show.end_time <= end_datetime)
    if min_price:
        query = query.filter(Show.ticket_price >= int(min_price))
    if max_price:
        query = query.filter(Show.ticket_price <= int(max_price))

    venues = Venue.query.all()
    shows = query.all()
    users = User.query.all()
    bookings = Booking.query.all() if current_user.role == "admin" else current_user.bookings

    return render_template("user/dashboard.html", venues=venues, shows=shows, bookings=bookings, users=users)


# Static part of rating (2 points) calculated at show creation
def calculate_static_rating(start_time, end_time, price):
    rating = 0

    duration = (end_time - start_time).seconds / 3600
    optimal_duration = 2.5
    rating += max(1 - abs(duration - optimal_duration) / optimal_duration, 0)

    optimal_price = 500

    if price <= optimal_price:
        rating += 1
    else:
        rating += max(1 - (price - optimal_price) / optimal_price, 0)  # rating of 0  at twice the optimal price
    return round(rating, 2)

application/templates/show/register.html
{% extends "base.html" %}
{% block title %}
Register Show
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">Register a Show</h1>
    <form action="{{ url_for('show.register') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.tags.label(class="form-label") }}
            {{ form.tags(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.ticket_price.label(class="form-label") }}
            {{ form.ticket_price(class="form-control") }}
        </div>
        {% if venue_id %}
        <div class="form-group">
            {{ form.venue_id.label(class="form-label") }}
            {{ form.venue_id(class="form-control", value=venue_id)}}
        </div>
        {% else %}
        <div class="form-group">
            {{ form.venue_id.label(class="form-label") }}
            {{ form.venue_id(class="form-control") }}
        </div>
        {% endif %}
        <div class="form-group">
            {{ form.start_time.label(class="form-label") }}
            {{ form.start_time(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.end_time.label(class="form-label") }}
            {{ form.end_time(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
        </div>
        {% if venue_id %}
        <input type="hidden" name="venue_id" value="{{venue_id}}">
        {%endif%}
        <!--Used just to pass the venue_id in post request-->
        <button type="submit" class="btn btn-primary mt-3">{{ form.submit.label }}</button>
    </form>
</div>
{% endblock %}

application/templates/show/show.html
{% extends "base.html" %}
{% block title %}
Show Details
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">{{ show.name }}</h1>
    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title">Show Details</h5>
            <table class="table table-bordered">
                <tbody>

                    <tr>
                        <th scope="row">Show Name</th>
                        <td>{{ show.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Rating</th>
                        <td>{{ show.rating|round(2) }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Tags</th>
                        <td>{{ show.tags }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Venue Name</th>
                        <td><a href="{{url_for('venue.venue',id=show.venue.id)}}">{{ show.venue.name }}</a></td>
                    </tr>
                    <tr>
                        <th scope="row">Ticket Price</th>
                        <td>{{ show.ticket_price }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Start Time</th>
                        <td>{{ show.start_time }}</td>
                    </tr>
                    <tr>
                        <th scope="row">End Time</th>
                        <td>{{ show.end_time }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Description</th>
                        <td>{{ show.description }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="container">
        <h2 class="my-4">Book Tickets</h2>
        {%if show.unsold_tickets %}
        <form action="{{url_for('booking.register',show_id=show.id)}}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.num_tickets.label(class="form-label") }}
                {{ form.num_tickets(class="form-control") }}
            </div>
            <input type="hidden" name="venue_id" value="{{show.venue.id}}">
            <button type="submit" class="btn btn-primary mt-3">{{ form.submit.label }}</button>
        </form>
        {%else%}
        <p class="text-danger font-weight-bold">Sold Out!</p>
        {%endif%}
    </div>

    <section>
        <div class="row my-4">
            <div class="col-md-12">
                <h2>Bookings</h2>
            </div>
        </div>
        <div class="row">
            {% for booking in current_user.bookings %}
            {% if booking.show.id == show.id %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ show.name }}
                        </h5>
                        <p class="card-text">
                            Number of tickets: {{ booking.num_tickets }}
                        </p>
                        <p class="card-text">
                            Date and time: {{ booking.show.start_time.strftime('%-d %b %-I%p') }}
                        </p>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

application/templates/show/show_admin.html
{% extends "base.html" %}
{% block title %}
Show Details
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">{{ show.name }}</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Show Details</h5>
            <form action="{{ url_for('show.show',id=show.id) }}" method="post" class="mb-2">
                {{ form.hidden_tag() }}
                <table class="table table-bordered">
                    <tbody>

                        <tr>
                            <th scope="row">Show Name</th>
                            <td>{{ show.name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Rating</th>
                            <td>{{ show.rating }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.tags.label}}</th>
                            <td>{{ form.tags }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Venue Name</th>
                            <td><a href="{{url_for('venue.venue',id=show.venue.id)}}">{{ show.venue.name }}</a></td>
                        </tr>
                        <tr>
                            <th scope="row">Ticket Price</th>
                            <td>{{ show.ticket_price }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Start Time</th>
                            <td>{{ show.start_time }}</td>
                        </tr>
                        <tr>
                            <th scope="row">End time</th>
                            <td>{{ show.end_time }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Created at</th>
                            <td>{{ show.created_at }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Sold Tickets</th>
                            <td>{{ show.sold_tickets }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.description.label}}</th>
                            <td>{{ form.description }}</td>
                        </tr>

                    </tbody>
                </table>
                <button class="btn btn-primary">Apply Changes</button>
            </form>
            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete
                Show</button>
        </div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Show</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this show? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{{ url_for('show.delete',id=show.id) }}" method="POST">
                    {{ form.hidden_tag() }}
                    <input type="submit" value="Delete Show" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}