application/forms/venue_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Email, Length, Regexp

from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, Regexp


class RegistrationForm(FlaskForm):
    name = StringField("Venue Name*", validators=[DataRequired(), Length(min=2, max=80)])
    capacity = IntegerField("Capacity*", validators=[DataRequired()])
    city = StringField("City*", validators=[DataRequired(), Length(min=2, max=20)])
    state = StringField("State*", validators=[DataRequired(), Length(min=2, max=20)])
    mobile_number = StringField(
        "Mobile Number*",
        validators=[DataRequired(), Regexp(r"^\d{10}$", message="Mobile number must be exactly 10 digits")],
    )
    email = StringField("Email*", validators=[DataRequired(), Email()])
    description = TextAreaField("Description", validators=[Length(max=200)])
    submit = SubmitField("Create Venue")


class EditForm(FlaskForm):
    mobile_number = StringField(
        "Mobile Number", validators=[Regexp(r"^\d{10}$", message="Mobile number must be exactly 10 digits")]
    )
    email = StringField("Email", validators=[Email()])
    description = TextAreaField("Description", validators=[Length(max=200)])

    name = StringField("Venue Name", validators=[Length(min=2, max=80)])
    city = StringField("City", validators=[Length(min=2, max=20)])
    state = StringField("State", validators=[Length(min=2, max=20)])

    submit = SubmitField("Apply Changes")

application/views/venue_views.py
from flask import request, redirect, url_for, render_template, Blueprint, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, current_user
from application.forms.venue_forms import RegistrationForm, EditForm
from application.models import User, Venue, Show, Booking
from application.database import db
from application.decorators import admin_required

venue_bp = Blueprint("venue", __name__)

# prefix of /venue has been applied for this blueprint


@venue_bp.route("/register", methods=["GET", "POST"])  # Create a new venue
@login_required
@admin_required
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_venue = Venue(
            name=form.name.data,
            capacity=form.capacity.data,
            city=form.city.data,
            state=form.state.data,
            mobile_number=form.mobile_number.data,
            email=form.email.data,
            description=form.description.data,
        )
        db.session.add(new_venue)
        try:
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            if "UNIQUE constraint failed: venue.name" in str(e):
                flash("Registration unsuccessful: Name already exists", "warning")
            if "UNIQUE constraint failed: venue.email" in str(e):
                flash("Registration unsuccessful: Email already exists", "warning")
            if "UNIQUE constraint failed: venue.mobile_number" in str(e):
                flash("Registration unsuccessful: Mobile number already exists", "warning")
            return redirect(url_for("venue.register"))
        flash("Venue registered successfully!", "success")
        return redirect(url_for("user.dashboard"))
    elif request.method == "POST":
        for field_name, field in form._fields.items():
            if field.errors:
                for error in field.errors:
                    flash(f"{field.label.text} error: {error}", "warning")
    return render_template("venue/register.html", form=form)


@venue_bp.route("/<int:id>", methods=["GET", "POST"])
# render venue page as well allow edits (edit button should be showed only for admins)!
@login_required  # may have to redirect role="user" post requests to some error page
def venue(id):
    venue = Venue.query.get_or_404(id)
    # Venue not found error shouldn't be possible as the link will be displayed only if the show exists but handle it using some error page ig
    form = EditForm()
    if current_user.role == "user":  # even if user sends post req...only non editable page will be displayed
        return render_template("venue/venue.html", venue=venue)
    else:
        if form.validate_on_submit():
            venue = Venue.query.get(id)
            venue.name = form.name.data
            venue.email = form.email.data
            venue.mobile_number = form.mobile_number.data
            venue.description = form.description.data
            venue.city = form.city.data
            venue.state = form.state.data

            try:  # db constraints validations
                db.session.commit()
            except IntegrityError as e:
                db.session.rollback()
                if "UNIQUE constraint failed: venue.name" in str(e):
                    flash("Edit unsuccessful: Venue Name already exists", "warning")
                if "UNIQUE constraint failed: venue.mobile_number" in str(e):
                    flash("Edit unsuccessful: Mobile number already exists", "warning")
                if "UNIQUE constraint failed: venue.email" in str(e):
                    flash("Edit unsuccessful: Email already exists", "warning")
                return redirect(url_for("venue.venue", id=id))
            flash("Edit successful!", "success")  # (message,category)
            return redirect(url_for("venue.venue", id=id))
        elif request.method == "POST":
            for field_name, field in form._fields.items():
                if field.errors:
                    for error in field.errors:
                        flash(f"{field.label.text} error: {error}", "warning")
    form.process(obj=venue)  # display editable venue page for admin get request
    return render_template("venue/venue_admin.html", venue=venue, form=form)


@venue_bp.route("/delete/<int:id>", methods=["POST"])
@login_required
@admin_required
def delete(id):
    venue = Venue.query.get_or_404(id)

    if venue.shows:
        # If shows are associated with the venue, return an error message
        flash(
            "Cannot delete a venue with associated shows. Please remove all shows before deleting the venue.", "danger"
        )
        return redirect(url_for("venue.venue", id=id))

    # If no shows are associated, delete the venue and redirect back to the dashboard
    db.session.delete(venue)
    try:
        db.session.commit()
        flash("Venue successfully deleted.", "success")
        return redirect(url_for("user.dashboard"))
    except Exception as e:
        flash("Error in deleting venue", "warning")
        return redirect(url_for("venue.venue", id=id))


@venue_bp.route("/filter")
@login_required
def filter():
    name = request.args.get("name", None)
    city = request.args.get("city", None)
    state = request.args.get("state", None)

    query = Venue.query

    if name:
        query = query.filter(Venue.name == name)
    if city:
        query = query.filter(Venue.city == city)
    if state:
        query = query.filter(Venue.state == state)

    venues = query.all()
    shows = Show.query.all()
    users = User.query.all()
    bookings = Booking.query.all() if current_user.role == "admin" else current_user.bookings

    return render_template("user/dashboard.html", venues=venues, shows=shows, bookings=bookings, users=users)

application/templates/venue/register.html
{% extends "base.html" %}
{% block title %}
Register Venue
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">Register a Venue</h1>
    <form action="{{ url_for('venue.register') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.capacity.label(class="form-label") }}
            {{ form.capacity(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.city.label(class="form-label") }}
            {{ form.city(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.state.label(class="form-label") }}
            {{ form.state(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.mobile_number.label(class="form-label") }}
            {{ form.mobile_number(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary mt-3">{{ form.submit.label }}</button>
    </form>
</div>
{% endblock %}

application/templates/venue/venue.html
{% extends "base.html" %}
{% block title %}
Venue Details
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">{{ venue.name }}</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Venue Details</h5>
            <table class="table table-bordered">
                <tbody>

                    <tr>
                        <th scope="row">Venue Name</th>
                        <td>{{ venue.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">City</th>
                        <td>{{ venue.city }}</td>
                    </tr>
                    <tr>
                        <th scope="row">State</th>
                        <td>{{ venue.state }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Capacity</th>
                        <td>{{ venue.capacity }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Mobile Number</th>
                        <td>{{ venue.mobile_number }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email</th>
                        <td>{{ venue.email }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Description</th>
                        <td>{{ venue.description }}</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
    <section>
        <div class="row my-4">
            <div class="col-md-3">
                <h2>Shows</h2>
            </div>
        </div>
        <div class="row">
            {% for show in venue.shows%}
            <div class="col-md-5 col-lg-3 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{url_for('show.show', id=show.id)}}">{{ show.name }}</a> {{ show.rating|round(2)
                            }}/5.0
                        </h5>
                        <p class="card-text">
                            {{ show.tags }}
                        </p>
                        <p class="card-text">
                            Price: ${{ show.ticket_price }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</div>

{% endblock %}

application/templates/venue/venue_admin.html
{% extends "base.html" %}
{% block title %}
Venue Details
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">{{ venue.name }}</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Venue Details</h5>
            <form action="{{ url_for('venue.venue',id=venue.id) }}" method="post" class="mb-2">
                {{ form.hidden_tag() }}
                <table class="table table-bordered">
                    <tbody>

                        <tr>
                            <th scope="row">{{form.name.label}}</th>
                            <td>{{ form.name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.city.label}}</th>
                            <td>{{ form.city }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.state.label}}</th>
                            <td>{{ form.state}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Capacity</th>
                            <td>{{ venue.capacity }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.mobile_number.label}}</th>
                            <td>{{ form.mobile_number }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.email.label}}</th>
                            <td>{{ form.email }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Created at</th>
                            <td>{{ venue.created_at }}</td>
                        </tr>
                        <tr>
                            <th scope="row">{{form.description.label}}</th>
                            <td>{{ form.description }}</td>
                        </tr>

                    </tbody>
                </table>
                <button class="btn btn-primary">Apply Changes</button>
            </form>
            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete
                Venue</button>
        </div>
    </div>
    <section>
        <div class="row my-4">
            <div class="col-md-3">
                <h2>Shows</h2>
            </div>
            <div class="col-md-9 d-flex justify-content-end align-items-center">
                <a href="{{url_for('show.register',id=venue.id)}}" class="btn btn-primary btn-sm me-3">Add Show</a>
            </div>
        </div>

        <div class="row">
            {% for show in venue.shows%}
            <div class="col-md-5 col-lg-3 mb-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{url_for('show.show', id=show.id)}}">{{ show.name }}</a> {{ show.rating }}/5.0
                        </h5>
                        <p class="card-text">
                            {{ show.tags }}
                        </p>
                        <p class="card-text">
                            Price: ${{ show.ticket_price }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </section>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Venue</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this venue? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{{ url_for('venue.delete',id=venue.id) }}" method="POST">
                    {{ form.hidden_tag() }}
                    <input type="submit" value="Delete Venue" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}